---
title: "ChekhovPlays"
author: "Miranda Lupion"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE)

# Load libraries
library(tidyverse)
library(ggplot2)
library(readr)
library(stringr)
library(scales)
library(knitr)
library(kableExtra)
library(ggrepel)
```

```{r data load}

# Load data

counts_real <- read_csv("counts_real_places.csv") %>%
  mutate(period = case_when(
    act == "Act I" ~ 1,
    act == "Act II" ~ 2,
    act == "Act III" ~ 3,
    act == "Act IV" ~ 4
  ))

```


```{r all plays}

# Summarize data across the four plays

counts_total <- counts_real %>%
  group_by(object) %>%
  summarise(total = sum(mentions)) %>%
  ungroup() 

# Reorder

counts_total <-counts_total[order(counts_total$total), ] 
counts_total$object <- factor(counts_total$object, levels = counts_total$object)

# Graph

counts_total %>%
  ggplot(aes(x = reorder(object, -total), y = total, label = total)) +
  geom_segment(aes(x = object, 
                   xend = object,
                   y = 0,
                   yend = total),
                   color = ifelse(counts_total$object %in% 
                                c("Moscow","Kharkov", "Paris"), "darkgreen", "skyblue"),
                   size = .75) +
  geom_point(color = ifelse(counts_total$object %in% 
                              c("Moscow","Kharkov", "Paris"), "darkgreen", "blue")) + 
  geom_label_repel(data = subset(counts_total, total > 9),
                   segment.size  = 0.2,
                   segment.color = "grey50",
                   nudge_y       = 5,
                  # direction     = "x",
                   hjust = 1) + 
  labs(title = "Mentions of Real Places Across the Four Plays") + 
  xlab("Place") +
  ylab("Counts") +
  theme_light() +
  ylim(0,55) +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()) 

```


```{r Vanya counts total}
#Uncle Vanya 

counts_real_vanya<- counts_real %>%
  filter(play == "Uncle Vanya") %>%
  group_by(object) %>%
  summarize(total = sum(mentions)) %>%
  ungroup()

# Reorder

counts_real_vanya <-counts_real_vanya[order(counts_real_vanya$total), ] 
counts_real_vanya$object <- factor(counts_real_vanya$object, levels = counts_real_vanya$object)

counts_real_vanya %>%
  ggplot(aes(x = reorder(object, -total), y = total)) + 
  geom_segment(aes(x = object, 
                   xend = object,
                   y = 0,
                   yend = total),
               color = "orange",
               size = 2) +
  geom_point(color = "orange", size = 4) + 
  xlab("Place") +
  ylab("Counts") + 
  labs(title = "Uncle Vanya, Mentions of Real Places") +
  ylim(0,4) +
  theme_light() +
  coord_flip() + 
  theme(
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank())
  

```
```{r Seagull counts total}

#Seagull

counts_real_gull<- counts_real %>%
  filter(play == "The Seagull") %>%
  group_by(object) %>%
  summarize(total = sum(mentions)) %>%
  ungroup()

# Reorder

counts_real_gull <-counts_real_gull[order(counts_real_gull$total), ] 
counts_real_gull$object <- factor(counts_real_gull$object, levels = counts_real_gull$object)

counts_real_gull %>%
  ggplot(aes(x = reorder(object, -total), y = total)) + 
  geom_segment(aes(x = object, 
                   xend = object,
                   y = 0,
                   yend = total),
               color = "navy",
               size = 2) +
  geom_point(color = "navy", size = 4) + 
  xlab("Place") +
  ylab("Counts") + 
  labs(title = "The Seagull, Mentions of Real Places") +
  #ylim(0,4) +
  theme_light() +
  coord_flip() + 
  theme(
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank())

```

```{r Three Sisters counts total}

#Sisters

counts_real_sis<- counts_real %>%
  filter(play == "Three Sisters") %>%
  group_by(object) %>%
  summarize(total = sum(mentions)) %>%
  ungroup()

# Reorder

counts_real_sis <-counts_real_sis[order(counts_real_sis$total), ] 
counts_real_sis$object <- factor(counts_real_sis$object, levels = counts_real_sis$object)

counts_real_sis %>%
  ggplot(aes(x = reorder(object, -total), y = total)) + 
  geom_segment(aes(x = object, 
                   xend = object,
                   y = 0,
                   yend = total),
               color = "pink",
               size = 2) +
  geom_point(color = "pink", size = 4) + 
  xlab("Place") +
  ylab("Counts") + 
  labs(title = "Three Sisters, Mentions of Real Places") +
  #ylim(0,4) +
  theme_light() +
  coord_flip() + 
  theme(
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank())

```


```{r Cherry Orchard counts}

#Cherry Orchard

counts_real_co<- counts_real %>%
  filter(play == "The Cherry Orchard") %>%
  group_by(object) %>%
  summarize(total = sum(mentions)) %>%
  ungroup()

# Reorder

counts_real_co <-counts_real_co[order(counts_real_co$total), ] 
counts_real_co$object <- factor(counts_real_co$object, levels = counts_real_co$object)

counts_real_co %>%
  ggplot(aes(x = reorder(object, -total), y = total)) + 
  geom_segment(aes(x = object, 
                   xend = object,
                   y = 0,
                   yend = total),
               color = "brown",
               size = 2) +
  geom_point(color = "brown", size = 4) + 
  xlab("Place") +
  ylab("Counts") + 
  labs(title = "The Cherry Orchard, Mentions of Real Places") +
  #ylim(0,4) +
  theme_light() +
  coord_flip() + 
  theme(
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank())

```







```{r Vanya counts by act}

crv<- counts_real %>%
  filter(play == "Uncle Vanya") %>%
  select(-period, -play) %>%
  spread(act, mentions) 

crv[is.na(crv)] <- 0

crv %>%  
kable(col.names = 
          c("Place", "Act I", "Act II", "Act III", "Act IV"),
        caption = "Place Mentions by Act, Uncle Vanya") %>%
  kable_styling(bootstrap_options = "striped")
  

```

